### PR TITLE
Upgrade to RabbitMQ 6.0.0

### PR DESCRIPTION
**Pull request by zgabi**

### CODE REVIEW

**Comment by eben-roux** [comment]
Thanks for the PR Gábor.  I'll get to it as soon as I can.  My home Internet was down from Friday 13h30 but up again today (Monday).

**Comment by zgabi** [comment]
Please do not merge it yet... I think there is a bug in it... i'm still investigating the problem.

**Comment by eben-roux** [comment]
> Please do not merge it yet... I think there is a bug in it... i'm still investigating the problem.

No problem.  I'll also take a look this weekend.

**Comment by zgabi** [comment]
I've investigated the problem, and it is not in this PR.
The new RabbitMQ using Task.Run. which is using ThreadPool.

And other part of our application (more exactly another 3rd party maps library) is also using ThreadPool, and some tasks are taking very long time (because of a bug), and no free threads for returning the messages.

So this PR should be OK, please check it when you have time.

**Pull request merged**
